DeustoFix/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DeustoFixapp.urls')),
]

DeustoFixapp/models.py
from django.db import models

class Instalacion(models.Model):
    nombre = models.CharField(max_length=100)
    tipo = models.CharField(max_length=50)
    tipo_uso = models.CharField(max_length=50, blank=True)
    ubicacion = models.CharField(max_length=100)
    capacidad =  models.IntegerField(null=True, blank=True)
    estado = models.CharField(max_length=20, default='Activa')
    departamento_responsable = models.CharField(max_length=100)
    
    def __str__ (self):
        return self.nombre
    
class Empleado(models.Model):
    dni = models.CharField(max_length=9, unique=True)
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    email = models.EmailField()
    telefono = models.CharField(max_length=15)
    
    def __str__ (self):
        return self.nombre

class Incidencia(models.Model):
    TIPO = [
        ('electrica', 'Eléctrica'),
        ('limpieza','Limpieza'),
        ('mobiliario','Mobiliario'),
        ('climatizacion','Climatización')
    ]
    
    URGENCIA = [
        ('alta','Alta'),
        ('media','Media'),
        ('baja','Baja')    
    ]
    
    ESTADO = [
        ('abierta','Abierta'),
        ('en curso', 'En curso'),
        ('resuelta', 'Resuelta'),
        ('cancelada', 'Cancelada')
    ]
    
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    tipo = models.CharField(max_length=20, choices=TIPO)
    nivel_urgencia = models.CharField(max_length=10, choices=URGENCIA)
    estado = models.CharField(max_length=15, choices=ESTADO, default='Abierta')
    fecha_apertura = models.DateField(auto_now_add=True)
    fecha_resolucion = models.DateField(blank=True, null=True)     
    
    instalacion = models.ForeignKey(Instalacion, on_delete=models.CASCADE)
    empleado_asignado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    
    def __str__ (self):
        return self.titulo

templates/DeustoFixappIncidencia/create_incidencia.html
{% extends "base.html" %}
{% block content %}
{% block titulo %} Crear Incidencia {% endblock %}
    <h2> Crear Incidencia </h2>
    <a href="{% url 'menu_incidencia' %}">Volver al menú de incidencias</a>
    <form method="post" class="Incidencia-form">
        {% csrf_token %}
        {% for field in form %}
        <div class="prueba">
            {{field.errors}}
            <label class="Incidencia-label" form="{{field.id_for_label}}">{{ field.label }}</label>
            {{field}}
            {% if field.help.text %}
            <p class="help">
                {{field.help.text|safe}}
            </p> 
            {% endif %}
        </div>
        {% endfor %}
        <input type="submit" class="boton" value="Nueva Incidencia">
    </form>
{% endblock %}

templates/DeustoFixappIncidencia/detail_incidencia.html
{% extends "base.html" %}
{% block titulo %} Detalle de Incidencia {% endblock titulo %} 
{% block content %}
    <h2>Detalles de la Incidencia</h2>
    <p><strong>Título:</strong> {{ incidencia.titulo }}</p>
    <p><strong>Descripción:</strong> {{ incidencia.descripcion }}</p>
    <p><strong>Tipo:</strong> {{ incidencia.get_tipo_display }}</p>
    <p><strong>Urgencia:</strong> {{ incidencia.get_nivel_urgencia_display }}</p>
    <p><strong>Estado:</strong> {{ incidencia.get_estado_display }}</p>
    <p><strong>Fecha de apertura:</strong> {{ incidencia.fecha_apertura }}</p>
    <p><strong>Fecha de resolución:</strong> {% if incidencia.fecha_resolucion %}{{ incidencia.fecha_resolucion }}{% else %}No resuelta{% endif %}</p>

    <a href="{% url 'list_incidencia' %}">Volver al listado de incidencias</a>
{% endblock %}

templates/DeustoFixappIncidencia/incidencia_detail.html
{% extends "base.html" %}
{% block titulo %} Detalle de Incidencia {% endblock titulo %} 
{% block content %}
    <h2>Detalles de la Incidencia</h2>
    <p><strong>Título:</strong> {{ incidencia.titulo }}</p>
    <p><strong>Descripción:</strong> {{ incidencia.descripcion }}</p>
    <p><strong>Tipo:</strong> {{ incidencia.get_tipo_display }}</p>
    <p><strong>Urgencia:</strong> {{ incidencia.get_nivel_urgencia_display }}</p>
    <p><strong>Estado:</strong> {{ incidencia.get_estado_display }}</p>
    <p><strong>Fecha de apertura:</strong> {{ incidencia.fecha_apertura }}</p>
    <p><strong>Fecha de resolución:</strong> {% if incidencia.fecha_resolucion %}{{ incidencia.fecha_resolucion }}{% else %}No resuelta{% endif %}</p>
    <a href="{% url 'list_incidencia' %}">Volver al listado de incidencias</a>
{% endblock %}

templates/DeustoFixappIncidencia/list_incidencia.html
{% extends "base.html" %}
{% block content %}
{% block titulo %} Listado de Incidencias {% endblock titulo %} 
<h2> Listado </h2>
<a href="{% url 'menu_incidencia' %}">Volver al menú de incidencias</a>
<ul>
    {% for incidencia in object_list %}
    <li>
        
        {{incidencia.titulo}}, Apertura: {{ incidencia.fecha_apertura}}, Empelado: {{incidencia.empleado_asignado.nombre}} ,Resolucion:  {{incidencia.fecha_resolucion}}, {{incidencia.empleado_aginado}} , <a href="{% url 'incidencia_detail' incidencia.pk %}">Detalle_Incidencia</a></p>, <a href="{% url 'delete_incidencia' incidencia.pk %}">Borrar Incidencia</a>
       
    </li>
    {% empty %}
        <li> No hay incidencias registradas </li>
    {% endfor %}
</ul>

{% endblock content %}

templates/DeustoFixappIncidencia/menu_incidencia.html
{% extends "base.html" %}

{% block content %}
    <h1>Bienvenido al Menú de Incidencias</h1>
    <p>Desde aquí puedes gestionar las incidencias.</p>
    <a href="{% url 'create_incidencia' %}">Crear nueva Incidencia</a>
    <a href="{% url 'list_incidencia' %}">Lista de Incidencias</a>
    <a href="{% url 'menu_principal' %}">Menu Principal</a>
{% endblock %}